version: '3.8'

services:
  notes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - notes_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - notes-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: notes-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - notes-app
    restart: unless-stopped
    networks:
      - notes-network
    profiles:
      - production

volumes:
  notes_data:
    driver: local

networks:
  notes-network:
    driver: bridge
